// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTiQ7TapTV5gxlLAEI2ROGBZkEuUC-Nq4',
    appId: '1:862865865411:web:71f8b218101d877782c076',
    messagingSenderId: '862865865411',
    projectId: 'resto-e9508',
    authDomain: 'resto-e9508.firebaseapp.com',
    storageBucket: 'resto-e9508.firebasestorage.app',
    measurementId: 'G-PX2R8PNS49',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdL6saBKx2XSlXhVkZ-MW2s6UP2Uy5BBI',
    appId: '1:862865865411:android:a9b81ee01884b25782c076',
    messagingSenderId: '862865865411',
    projectId: 'resto-e9508',
    storageBucket: 'resto-e9508.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACgaD0qjtE-jiGXpmDRTPsuO2flWfjcmg',
    appId: '1:862865865411:ios:63f3e9113e8b406a82c076',
    messagingSenderId: '862865865411',
    projectId: 'resto-e9508',
    storageBucket: 'resto-e9508.firebasestorage.app',
    iosBundleId: 'com.codingaja.resto',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACgaD0qjtE-jiGXpmDRTPsuO2flWfjcmg',
    appId: '1:862865865411:ios:63f3e9113e8b406a82c076',
    messagingSenderId: '862865865411',
    projectId: 'resto-e9508',
    storageBucket: 'resto-e9508.firebasestorage.app',
    iosBundleId: 'com.codingaja.resto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTiQ7TapTV5gxlLAEI2ROGBZkEuUC-Nq4',
    appId: '1:862865865411:web:f7f916e34308bb4e82c076',
    messagingSenderId: '862865865411',
    projectId: 'resto-e9508',
    authDomain: 'resto-e9508.firebaseapp.com',
    storageBucket: 'resto-e9508.firebasestorage.app',
    measurementId: 'G-V3YMZJYQW6',
  );
}
